![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [4]:
import numpy as np 
np.__version__

'1.21.6'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [17]:
lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
my_array = np.array(lista)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [16]:
m = np.array([[True, True, True], [True, True, True], [True, True, True]])

print(m)

np.full((3,3),True)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [16]:
for n in my_array:
    if n%2 != 0:
        print(n)

my_array[my_array %2 != 0]

1
3
5
7
9


array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [24]:
my_array[my_array %2 !=0]=-1

print(my_array)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [27]:
second_array = np.arange(10)
print(second_array)

new_array = np.where(second_array %2 != 0, -1, second_array)
print(new_array)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [36]:
years = np.arange(1600, 2023)

mask_bis = (((years % 4 == 0) & (years % 100 != 0)) | (years % 400 == 0) )

years[mask_bis] = 999

print(years)



[ 999 1601 1602 1603  999 1605 1606 1607  999 1609 1610 1611  999 1613
 1614 1615  999 1617 1618 1619  999 1621 1622 1623  999 1625 1626 1627
  999 1629 1630 1631  999 1633 1634 1635  999 1637 1638 1639  999 1641
 1642 1643  999 1645 1646 1647  999 1649 1650 1651  999 1653 1654 1655
  999 1657 1658 1659  999 1661 1662 1663  999 1665 1666 1667  999 1669
 1670 1671  999 1673 1674 1675  999 1677 1678 1679  999 1681 1682 1683
  999 1685 1686 1687  999 1689 1690 1691  999 1693 1694 1695  999 1697
 1698 1699 1700 1701 1702 1703  999 1705 1706 1707  999 1709 1710 1711
  999 1713 1714 1715  999 1717 1718 1719  999 1721 1722 1723  999 1725
 1726 1727  999 1729 1730 1731  999 1733 1734 1735  999 1737 1738 1739
  999 1741 1742 1743  999 1745 1746 1747  999 1749 1750 1751  999 1753
 1754 1755  999 1757 1758 1759  999 1761 1762 1763  999 1765 1766 1767
  999 1769 1770 1771  999 1773 1774 1775  999 1777 1778 1779  999 1781
 1782 1783  999 1785 1786 1787  999 1789 1790 1791  999 1793 1794 1795
  999 

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [45]:
print(my_array)

y= my_array.reshape((2,5))
print(y)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [13]:
print(a)
print(b)
np.vstack([a,b])
np.hstack([a,b])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [49]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(a)
print(b)

np.hstack([a,b])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [54]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a, b, assume_unique=False, return_indices=False)

print(c)

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [58]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [17]:
list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
my_array = np.array(list)
print(my_array)

#APARTADO 1
new_array = my_array * 10
print(new_array)

#APARTADO 2
print(my_array[0])

#APARTADO 3
print(my_array[-1])

#APARTADO 4
print(my_array[1:8])

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [5]:
my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
                     
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [21]:
x = np.arange(50)
print(x[1::3])

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [33]:
print(np.arange(4,1,-0.25))

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

In [7]:
from skimage.io import imread
import matplotlib.pyplot as plt

imagen = imread('./img/numpy.png')

print(imagen.shape)

plt.imshow(imagen)


FileNotFoundError: No such file: 'c:\Users\usuario\Desktop\img\numpy.png'

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [65]:
array_17 = np.random.randint(0,9, size = (4,1))
print(array_17)

y = array_17.reshape((2,2))
print(y)

[[0]
 [3]
 [0]
 [6]]
[[0 3]
 [0 6]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [27]:
x = np.random.randint(0,9, size = (4,5,3))
print(x)
x.ndim

[[[7 3 4]
  [6 8 1]
  [3 7 2]
  [5 6 8]
  [3 5 4]]

 [[8 3 1]
  [1 1 4]
  [8 5 5]
  [1 5 7]
  [7 6 0]]

 [[5 6 5]
  [8 0 4]
  [5 4 0]
  [1 1 3]
  [0 3 4]]

 [[5 5 0]
  [1 2 1]
  [6 0 3]
  [7 7 5]
  [7 8 2]]]


3

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [72]:
array_19 = np.full((10,1), False)
print(array_19)

print("\n")

y=array_19.reshape(2,5)
print(y)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]


[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [8]:
x = np.random.randint(10,20, size = (5,2,6))
print(x)
#Este array tiene 60 elementos
#Tiene 3 dimensiones
x.ndim 
print(x.shape)


[[[19 10 15 17 14 18]
  [17 19 16 14 11 15]]

 [[12 13 16 15 19 15]
  [15 18 13 17 16 19]]

 [[11 18 16 17 18 14]
  [12 13 13 14 14 17]]

 [[11 11 16 12 18 15]
  [14 17 17 14 10 11]]

 [[15 18 19 10 13 15]
  [11 14 11 12 18 14]]]
(5, 2, 6)
