![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [18]:
import numpy as np
my_array = np.arange(0,10)
print(my_array)
print(my_array[9::-2] )

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [32]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [25]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [43]:
matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(matrix)
print("\n")

print(np.flip(matrix,0))
print("\n")

print(np.flip(matrix, 1))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [59]:
ej_5 = np.array(matrix[:2,:2])
ej_5

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [61]:
ej_6 = np.array(matrix[::2,::2])
ej_6

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [94]:
ej_7 = np.array(matrix[:3,::-1])
ej_7

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [76]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x)

mask = ( x == "Loro")
print(mask)

x_loro = x[x == "Loro"]
print(x_loro)

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']
[ True False False  True False]
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [91]:
x = np.arange(1,21)
print(x)

print("\n")

y = x.reshape(2,5,2)
print(y)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [97]:
print(matrix)

print("\n")

ej_10 = np.array(matrix[::-1,::-1])
print(ej_10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [105]:
ej_11 = np.zeros(10)
print(ej_11)

print(ej_11.nbytes)

ej_11[3] = 1
print(ej_11)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [108]:
ej_12 = np.arange(10,50)
print(ej_12)
print(ej_12[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [9]:
a = np.array([1,2,0,0,4,0])
print(a)

print(np.where((a != 0 )))


[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [114]:
ej_14 = np.random.randint(0,101, size = (10,10))
print(ej_14)

np.min(ej_14), np.max(ej_14)

[[35 31 54  8 53 50 88 34 40 63]
 [41  9 84 30 23 42 97 27 71 88]
 [96 86 46 83  5 20 61 87 10  4]
 [79 16 65  0 59 83 16 32 83 41]
 [79 58 84 30 47 42 35  9 81 84]
 [80 55 38  3 64 50 47 80 74 36]
 [12 16  2 67 72 16 24 12 16  6]
 [26 54 45 96  2 41 25 87 86  7]
 [91 58 83 33 23 83 80 95 43 28]
 [16 45 59 39 62 83 38 29 28 15]]


(0, 97)

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [120]:
ej_15 = np.random.randint(0,100,30)
print(ej_15)
np.mean(ej_15)

[43 19 46 12 10 61 25  4 73 69 72 13 71 59 38 44 10 30  2  9 87 65 46 83
 22  4  0 80 88 67]


41.733333333333334

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [138]:
ej_16 = np.zeros((3,3))
print(ej_16)

print("\n")

ej_16[0]=1
ej_16[2]=1
ej_16[1,::2]=1
print(ej_16)

# He llegado al resultado pero debe de haber una manera más fácil y rápida, ya que si las dimensiones hubieran sido más grandes resultaría
# imposible de hacer con este método

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [12]:
ej_17 = np.zeros((8,8))
print(ej_17)

print("\n")

ej_17[0::2,1::2] = 1
print(ej_17)

print("\n")

ej_17[1::2,0::2] = 1
print(ej_17)



[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [15]:
np.tile(ej_17, 1)

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 9
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [8]:
ej_19 = np.random.randint(0,21, size = (5,5))
print(ej_19)

print("\n")

mean = np.mean(ej_19)
print(mean)

print("\n")

deviation = np.std(ej_19)
print(deviation)

print("\n")

m = np.full((5,5),mean)
print(m)

print("\n")

d = np.full((5,5), deviation)
print(d)

print("\n")

matrix_normalizada = (ej_19 - m )/d
print(matrix_normalizada)
 
 

[[15 18 16  8  0]
 [ 3 10  8 13  2]
 [18 10 11  7 19]
 [16 16 13 13  9]
 [11 15  1  0 16]]


10.72


5.76555287895272


[[10.72 10.72 10.72 10.72 10.72]
 [10.72 10.72 10.72 10.72 10.72]
 [10.72 10.72 10.72 10.72 10.72]
 [10.72 10.72 10.72 10.72 10.72]
 [10.72 10.72 10.72 10.72 10.72]]


[[5.76555288 5.76555288 5.76555288 5.76555288 5.76555288]
 [5.76555288 5.76555288 5.76555288 5.76555288 5.76555288]
 [5.76555288 5.76555288 5.76555288 5.76555288 5.76555288]
 [5.76555288 5.76555288 5.76555288 5.76555288 5.76555288]
 [5.76555288 5.76555288 5.76555288 5.76555288 5.76555288]]


[[ 0.74233991  1.26267162  0.91578381 -0.47176742 -1.85931865]
 [-1.33898694 -0.12487961 -0.47176742  0.3954521  -1.51243084]
 [ 1.26267162 -0.12487961  0.04856429 -0.64521132  1.43611553]
 [ 0.91578381  0.91578381  0.3954521   0.3954521  -0.29832351]
 [ 0.04856429  0.74233991 -1.68587475 -1.85931865  0.91578381]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [34]:
ej_10 = np.arange(0,11)
print(ej_10)

ej_10[4:8]=-1
print(ej_10)

mask = (ej_10 != -1)
print(mask)


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[ True  True  True  True False False False False  True  True  True]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [38]:
tablero = np.full((10,10),(" "))
barco = "0"
tablero[0,1]= barco
tablero[1,1]= barco
tablero[1,3]= barco
tablero[1,4]= barco
tablero[1,5]= barco
tablero[1,6]= barco

print(tablero)
print("\n")

disparo = "X"
tablero[1,3]= disparo
tablero[1,4]= disparo
tablero[1,5]= disparo
tablero[1,6]= disparo

print(tablero)

[[' ' '0' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' '0' ' ' '0' '0' '0' '0' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


[[' ' '0' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' '0' ' ' 'X' 'X' 'X' 'X' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
[[' ' '0' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' '0' ' ' 'X' 'X' 'X' 'X' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' '

In [39]:
agua = "-"
tablero[5,5]= agua

print(tablero)

[[' ' '0' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' '0' ' ' 'X' 'X' 'X' 'X' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' '-' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
